RubyLint::CLI.options.command :ast do
  banner      'Usage: ruby-lint ast [FILE] [OPTIONS]'
  description 'Shows the AST of a Ruby file'

  separator <<-EOF.chomp

About:

  This command displays the raw AST of a Ruby file. Unlike the `analyze`
  command this particular one only takes a single file.

  The output is a set of S expressions generated by the ruby-lint parser
  (RubyLint::Parser).

Examples:

  Displaying the AST:

    $ ruby-lint ast ./test_file.rb
  EOF

  separator RubyLint::CLI::OPTIONS_HEADER

  RubyLint::CLI.help_option(self)

  ##
  # @return [IO]
  #
  def output_destination
    return @output_destination ||= STDOUT
  end

  ##
  # @param [IO] destination
  #
  def output_destination=(destination)
    @output_destination = destination
  end

  run do |opts, args|
    file = File.expand_path(args[0])

    abort 'You must specify an existing file' unless File.file?(file)

    code   = File.read(file)
    parser = RubyLint::Parser.new

    output_destination.puts parser.parse(code, file).inspect
  end
end
