RubyLint::CLI.options.command :ast do
  banner      'Usage: ruby-lint ast [FILE] [OPTIONS]'
  description 'Shows the AST of a Ruby file'

  separator <<-EOF.chomp

About:

  This command displays the raw AST of a Ruby file. Unlike the `analyze`
  command this particular one only takes a single file.

  The output is a set of S expressions generated by the ruby-lint parser
  (RubyLint::Parser).

Examples:

  Displaying the AST:

    $ ruby-lint ast ./test_file.rb
  EOF

  separator   RubyLint::CLI::OPTIONS_HEADER

  RubyLint::CLI.help_option(self)

  run do |opts, args|
    file = args[0]

    if !file or !File.file?(file)
      abort 'You must specify an existing file'
    end

    puts RubyLint::Parser.new(File.read(file), file).parse.inspect
  end
end
