module RubyLint
  ##
  # The Iterator class provides the means to iterate over an AST generated by
  # {RubyLint::Parser} using callback methods for the various node types
  # generated by this parser.
  #
  # For each node type two events are called: one before and one after
  # processing the node and all of its children. The names of these events are
  # the following:
  #
  # * `on_X`
  # * `after_X`
  #
  # Here "X" is the name of the event. For example, when iterator an integer
  # this would result in the event names `on_integer` and `after_integer`.
  #
  # These event names are used to call the corresponding callback methods if
  # they exist. Each callback method takes a single argument: the node (an
  # instance of {RubyLint::AST::Node}) that belongs to the event.
  #
  # Creating iterator classes is done by extending this particular class and
  # adding the needed methods to it:
  #
  #     class MyIterator < RubyLint::Iterator
  #       def on_int(node)
  #         puts node.children[0]
  #       end
  #
  #       def after_int(node)
  #         puts '---'
  #       end
  #     end
  #
  # When used this particular iterator class would display the values of all
  # integers it processes. After processing an integer it will display three
  # dashes.
  #
  class Iterator
    ##
    # Hash containing the options that were set for the iterator.
    #
    # @return [Hash]
    #
    attr_reader :options

    ##
    # @param [Hash] options Hash containing custom options to set for the
    #  iterator.
    #
    def initialize(options = {})
      options.each do |key, value|
        instance_variable_set("@#{key}", value)
      end

      after_initialize if respond_to?(:after_initialize)
    end

    ##
    # Recursively processes the specified list of nodes.
    #
    # @param [RubyLint::Node] node A node and optionally a set of sub nodes to
    #  iterate over.
    #
    def iterate(node)
      return unless node.is_a?(AST::Node)

      before, after = callback_names(node)

      execute_callback(before, node)

      node.children.each do |child|
        if child.is_a?(Array)
          child.each { |c| iterate(c) }
        else
          iterate(child)
        end
      end

      execute_callback(after, node)
    end

    protected

    ##
    # Executes the specified callback method if it exists.
    #
    # @param [String|Symbol] name The name of the callback method to execute.
    # @param [Array] args Arguments to pass to the callback method.
    #
    def execute_callback(name, *args)
      send(name, *args) if respond_to?(name)
    end

    ##
    # Returns an array containin the callback names for the specified node.
    #
    # @param [RubyLint::Node] node
    # @return [Array]
    #
    def callback_names(node)
      return ["on_#{node.type}", "after_#{node.type}"]
    end
  end # Iterator
end # RubyLint
