---
# http://stackoverflow.com/questions/36979283/how-to-fix-travis-error-nomethoderror-undefined-method-spec-for-nilnilclass
# https://github.com/travis-ci/travis-ci/issues/3531
before_install:
  - gem install bundler

script: bundle exec rake

rvm:
  - 2.0
  - 2.1
  - 2.2.5
  - rbx-2
  - jruby-9.1.5.0

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    email:
      on_success: change
      on_failure: always

cache: bundler

os:
  - linux
  - osx
# https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
# This gives us OSX 10.10 which does have jruby-9.x.x.x AND ruby-2.2.5
osx_image: xcode6.4
