---
sudo: false

script: bundle exec rake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libyaml-dev

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    email:
      on_success: change
      on_failure: always

cache: bundler

os:
  - linux
  - osx
