---
# http://stackoverflow.com/questions/36979283/how-to-fix-travis-error-nomethoderror-undefined-method-spec-for-nilnilclass
# https://github.com/travis-ci/travis-ci/issues/3531
before_install:
  - gem install bundler

script: bundle exec rake

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    email:
      on_success: change
      on_failure: always

cache: bundler

os:
  - linux
  - osx
