---
script: rake travis

rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    email:
      on_success: change
      on_failure: always

branches:
  only:
    - master
